#ifndef _i8042_H
#define _i8042_H



#define DELAY_US    20000

#define KBC_ADRESS 0x64
#define KBC_BUFF_ADRESS 0x60

#define BREAK_CODE 0x80
#define ESC_BREAK_CODE 0x81
#define SCAN_TWO_BYTES 0xE0

#define	KEYBOARD_LEDS_CMD 0xED

#define IKEYBOARD_IRQ 0x01

#define KEYBOARD_BUFF_ACK 0xFA
#define KEYBOARD_BUFF_RESEND 0xFE
#define KEYBOARD_BUFF_ERROR 0xFC

#define KEYBOARD_STATUS_PAR 0x80
#define KEYBOARD_STATUS_TIMEOUT 0x40
#define KEYBOARD_STATUS_INBUFF_FULL 0x02


#endif
